language: python

env:
  matrix:
    - TOX_ENV=py27-dj15
    - TOX_ENV=py27-dj16
    - TOX_ENV=py27-dj17
    - TOX_ENV=py27-dj18
    - TOX_ENV=py34-dj15
    - TOX_ENV=py34-dj16
    - TOX_ENV=py34-dj17
    - TOX_ENV=py34-dj18

python:
  - "2.7"
  - "3.4"

install:
  - pip install tox coverage coveralls

script:
  #- coverage run --source=djcelery_ses setup.py test
  - tox -e $TOX_ENV

after_success:
  - coveralls
